CREATE TABLE NoteTaker (
	ID INT CONSTRAINT PK_NoteTaker_ID PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(30),
	Text NVARCHAR(100),
	DateCreatedUTC datetime CONSTRAINT DF_NoteTaker_DateCreatedUTC DEFAULT GETUTCDATE()
);